# i_am = input('What are you?')
# i_want = input('What do you want?')
# i_worry = input("What do you worry about?")
# lucky_number1 = int(input('Enter a number from 1-25'))
# lucky_number2 = int(input('Enter a different number from 1-25'))
# i_understand = input('What do you understand?')
# i_feel = input('How do you feel?')
# i_dream = input('What do you dream of?')

# print('I am ', i_am)
# print('I want', i_want)
# print('I worry about', i_worry)
# print('My lucky number is', str(lucky_number1+lucky_number2))
# print('I understand', i_understand)
# print('I feel', i_feel)
# print('I dream of', i_dream)
print((3+2) % (1+1))